config/routes.rb
Documonk::Application.routes.draw do
  get "pages/home"

  get "pages/contact"

  devise_for :users
  
  root :to => 'documents#show', :id =>1
  
  resources :documents do
    resources :notes
  end
  resources :notes
  resources :users
  
  match '/new',  :to => 'documents#new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
     if user.role? :admin
       can :manage, :all
     else
       can :read, Document, :all
       can :create, Document
       can :update, Document do |document|
         document.try(:user) == user
       end
       can :destroy, Document do |document|
         document.try(:user) == user
       end
       can :read, User, :id => user.id
       can :update, User, :id => user.id
     end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
    attr_accessible :title, :content, :stats_code, :public

    belongs_to :user
    has_many :notes
   
    validates :title, :presence => true
    validates :content, :presence => true
    validates :user_id, :presence => true
end

app/models/note.rb
class Note < ActiveRecord::Base
    attr_accessible :content, :position, :note_type, :user_id, :document_id
    belongs_to :document
    belongs_to :user

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  #already in user.rb!
  #def role?(role)
 #   return !!self.roles.find_by_name(role.to_s.camelize)
 # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :twitter_account, :role_list
  
  has_many :documents, :dependent => :destroy
  has_many :notes
 
  has_and_belongs_to_many :roles

  #see http://ramblings.gibberishcode.net/archives/rails-has-and-belongs-to-many-habtm-demystified/17
  attr_accessor :role_list
  #after_save is called every time you create a new session? check this
  after_save :update_roles
  
  def role?(role)
    #see http://stackoverflow.com/questions/3994033/ruby-operator-a-k-a-the-double-bang
      return !!self.roles.find_by_name(role.to_s)
  end
  
  def role!()
    #hack: return "user" if no role is set -> should check this when user is created instead
    if self.roles[0].nil?
      return "user"
    else
      return self.roles[0].name
    end
  end
  
  protected
  
      def password_required?
        !persisted? || password.present? || password_confirmation.present?
      end
  
  private 

      def update_roles
        # puts "roles => #{role_list.inspect}"
        unless role_list.nil?
          roles.delete_all
          selected_roles = role_list.keys.collect{|id| Role.find_by_id(id)}
          selected_roles.each {|role| self.roles << role}
        end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def after_sign_in_path_for(resource)
    params[:redirect_to] || super
  end
  
  def after_sign_out_path_for(resource)
    params[:redirect_to] || super
  end
    
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  
  def index
    @document = Document.all
    authorize! :read, @document
  end
  
  def show
    @document = Document.find(params[:id])
  end

  def new
    @title = "Create new document"
    @document = current_user.documents.build(:title => 'My New Document', :content => 'This is your document\'s content. Click on the "view/edit" switch in the floating palette to get started!')
    #@document = Document.new :user => current_user, :title => 'New Document', :content => 'This is your document\'s content. Click on the "view/edit" switch in the floating palette to get started!'  
    @new=true
    render :action => 'show'
  end
  
  def create
    # @document = Document.new(params[:document])
    @document = current_user.documents.build(params[:document])
    if @document.save
        flash[:success] = "Document created successfully!"
        redirect_to @document 
    else
      @title = "Create new document"
      render 'new'
    end
  end
  
  def edit
    @document = Document.find(params[:id])
    @title = "Edit document"
    authorize! :update, @document
  end
  
  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      flash[:success] = "Document updated."
      redirect_to @document
    else
      @title = "Edit document"
      render 'edit'
    end
  end 
  
  def destroy
    Document.find(params[:id]).destroy
    flash[:success] = "Document destroyed."
    redirect_to user_path(current_user)
    authorize! :destroy, @document
  end

 
end

app/controllers/notes_controller.rb
class NotesController < InheritedResources::Base
  belongs_to :document
  
  def create
    @note = parent.notes.build(params[:note])
    @note.user = current_user
    create!
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
   # @user=current_user
  @document = Document.all
  end


  
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, :only => [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @title = "All users"
    @users = User.all
    authorize! :read, @user
  end

  def show
    @documents = @user.documents
  end

  
  def edit
    get_all_roles
    @title = "Edit user"
    authorize! :update, @user
  end

  def update
    get_all_roles
    #see http://www.tonyamoyal.com/2010/09/29/rails-authentication-with-devise-and-cancan-part-2-restful-resources-for-administrators/
    #if params[:user][:password].blank?
    #  [:password].collect{|p| params[:user].delete(p) }
    #end
    
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
 
  def get_all_roles
    @roles = Role.find(:all)
  end


  private
    
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
=begin
  def devise_error_messages!
      @devise_error_messages! ||= Devise.error_messages
  end
=end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => "alt-text",
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

    
end

app/views/documents/_aloha.html.erb
<%= javascript_include_tag 'aloha/aloha' %>
<%= javascript_include_tag 'aloha/plugins/com.gentics.aloha.plugins.Format/plugin' %>
<%= javascript_include_tag 'aloha/plugins/com.gentics.aloha.plugins.Table/plugin' %>
<%= javascript_include_tag 'aloha/plugins/com.gentics.aloha.plugins.Link/plugin' %>

<script type="text/javascript">
GENTICS.Aloha.settings = {
	logLevels: {'error': true, 'warn': true, 'info': true, 'debug': true}
	,errorhandling : false
	,ribbon: false	
	/*"i18n": {
		// let the system detect the users language
		//"acceptLanguage": '<?=$_SERVER['HTTP_ACCEPT_LANGUAGE']?>'
		"acceptLanguage": 'de-de,de;q=0.8,it;q=0.6,en-us;q=0.7,en;q=0.2'
	},*/
	/*"plugins": {
	 	"com.gentics.aloha.plugins.Link": {
		  	// all links that match the targetregex will get set the target
 			// e.g. ^(?!.*aloha-editor.com).* matches all href except aloha-editor.com
		  	targetregex : '^(?!.*aloha-editor.com).*',
		  	// this target is set when either targetregex matches or not set
		    // e.g. _blank opens all links in new window
		  	target : '_blank',
		  	// the same for css class as for target
		  	cssclassregex : '^(?!.*aloha-editor.com).*',
		  	cssclass : 'external'
		},
	 	"com.gentics.aloha.plugins.Table": {
			config: ['table']
		}
  	}*/
};
$().ready(function() {
	$('#document_content').aloha();
	

	$(".edit-link").click(function(){
		editables=GENTICS.Aloha.editables;
		if(editables.length>0){
			jQuery.each(editables,function (index, editable) {
				editable.enable();
			});
		}else{
			$("#content").aloha();
		}
		return false;
	});
	
	$(".finish-link").click(function(){
		jQuery.each(GENTICS.Aloha.editables,function (index, editable) {
			editable.disable();
		});
	//GENTICS.Aloha.Editable.disable()
	//		editable.deactivateEditable();
		console.log(GENTICS.Aloha.editables);
	});
	var content = "";
	// iterate all dom elements which have been made aloha editable

	jQuery.each(GENTICS.Aloha.editables,function (index, editable) {
		// and get their clean and valid html5 content, and remember it to fake saving 
		content = content + "Editable ID: " + editable.getId() +"\nHTML code: " + editable.getContents() + "\n\n";
	});
});
</script>

app/views/documents/_chili.html.erb
<%= javascript_include_tag 'chili/jquery.chili-2.2' %>
<%= javascript_include_tag 'chili/recipes' %>

<script type="text/javascript">
	ChiliBook.recipeFolder = "/javascripts/chili/";
	ChiliBook.automatic = true; 
ChiliBook.lineNumbers = true; 

$().ready(function() {
	$("code").chili();
});
</script> 

app/views/documents/_custom.html.erb
<%= javascript_include_tag 'jquery.scribe' %>

<script type="text/javascript">
$().ready(function() {
	$('#content').scribe.config();

	/*	
	$(".bold-link").click(function(){
		$('#content').scribe.doCommand("bold");		
		return false;
	});
	$(".italic-link").click(function(){
		$('#content').scribe.addTag("italic");		
		return false;
	});
	*/

});
</script>

app/views/documents/_document.html.erb
<li>
	<span class="content"><%= link_to document.title, document %></span> <span class="small">by <span class="user"><%= link_to document.user.email, document.user %></span></span><br/>
	<span class="timestamp small">Posted <%= time_ago_in_words(document.created_at) %> ago.</span>
	<% if can? :update, document %>
		<%= link_to "Edit", edit_document_path(document.id), :class => "small" %>
	<% end %>
	<% if can? :destroy, document %>
		| <%= link_to "Delete", document, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{document.title}",:class => "small delete"  %>
	<% end %>
</li>

app/views/documents/_highlight.html.erb
<% content_for :head do %>
<link rel="stylesheet" href="http://yandex.st/highlightjs/5.16/styles/default.min.css">
<script src="http://yandex.st/highlightjs/5.16/highlight.min.js"></script>

<script type="text/javascript">
	hljs.initHighlightingOnLoad();
</script>
<% end %>

app/views/documents/_palette.html.erb
<div id="palette" class="not-editing">
		<div class="top-bar">
			<% if user_signed_in? %>
				 <a href="/users/sign_out" class="logout button icon-button"><span>Log Out</span></a>
			<% else %>
				 <a href="/users/sign_in" class="login button icon-button"><span>Log In</span></a>
			<% end %>
			<% if can? :update, @document %>
				<a href='#' id="edit-switch" class="switch inactive-switch">
					<span class="indicator button"></span>
					<span class="option off">View</span>
					<span class="option on last">Edit</span>
				</a>
			<% end %>
			<a class="minmax minimize button icon-button"><span>Minimize</span></a>
		</div>
		<% if can? :update, @document %>
			<div class="edit-options">
				<a href='#' id="source-switch" class="switch inactive-switch">
					<span class="indicator button"></span>
					<span class="option off">Text</span>
					<span class="option on last">Code</span>
				</a>
				<div class="save">
					<span class="loader"></span>
					<span class="success-indicator"></span>
					<span class="error-indicator"></span>
					<a href="#" class="button save-button"><span>Save</span></a>
				</div>
			</div>
		<% end %>
		<div class="contents">
			<ul class="navigation">
				<li class="info first"><a href="#info"><span>Info</span></a></li>
				<li class="toc"><a href="#toc"><span>T.O.C.</span></a></li>
				<% if can? :update, @document %>
					<!--
					<li class="stats"><a href="#stats"><span>Stats</span></a></li>
					-->
					<li class="settings"><a href="#settings"><span>Settings</span></a></li>
					<li class="edit-only typography"><a href="#typography"><span>Typography</span></a></li>
				<% end %>
				<!--
				<li class="profile"><a href="#profile"><span>Profile</span></a></li>
				<li class="download"><a href="#download"><span>Download</span></a></li>
	
				<li class="edit last"><a class="edit-link" href="#edit"><span>Edit</span></a></li>
				-->
				<li class="fill"></li>
			</ul>
			<div id="info">
				<!--
				<h3>Informations</h3>
				-->
				<div class="content">
					<h4><%= @document.title %></h4>
					<% unless @document.user.twitter_account.nil? or @document.user.twitter_account=="" %>
						<p><strong>Author</strong>: <a href="http://twitter.com/<%= @document.user.twitter_account %>">@<%= @document.user.twitter_account %></a></p>
					<% end %>
					<% unless @document.updated_at.nil? %>
						<p class="small">Last updated: <%= time_ago_in_words(@document.updated_at) %> ago.</p>
						<%#= link_to "Download PDF", document_path(@document, :format => "pdf") %>	
					<% end %>
					<hr/>
					<div class="social-media">
						<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="Documonk">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
					
						<div class="facebook">
						<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" layout="button_count" show_faces="false" width="139" font=""></fb:like>
						</div>
					
					<iframe border="0" scrolling="no" width="78" height="17" allowtransparency="true" frameborder="0"
					 style="margin-bottom: -3px; z-index: 1338; border: 0px; background-color: transparent; overflow: hidden;"
					 src="http://www.instapaper.com/e2?url=<%= CGI.escape(request.url) %>&title=<%= CGI.escape(@document.title) %>"
					></iframe>

					</div>
					<hr/>
				
					<% if user_signed_in? %>
						<div class="user-info">
							<!--
							<p>Signed in as <strong><%= link_to current_user.email, user_path(current_user) %></strong></p>
							-->
							<ul>
								<li><%= link_to "My Documents", user_path(current_user) %></li>
								<li><%= link_to "My Account", edit_user_path(current_user) %></li>
								<li><%= link_to "Sign Out", destroy_user_session_path %></li>
							</ul>
					<p><a href="/documents/new" class="button">New document</a></p>
						</div>
					<% else %>
						<div class="docu-intro">
							<p>This document was written with <a href="/documents/1">Documonk</a>, a free service to create documents. Give it a try!<%#= link_to "Sign up now!", new_user_registration_path %></p>
							<p><a href="<%= new_user_registration_path %>" class="button">Create a document</a></p>
							<hr/>
							<p>Have an account? <%= link_to "Sign in", new_user_session_path, :class =>
"login" %></p>
						</div>
					<% end %>
				</div>
			</div>
			<div id="toc">
				<h3>Table of Contents</h3>
				<div class="content">
				<!--
				<h4><%= @document.title %></h4>
				-->
				<ol id="toc-inner"></ol>
				</div>
			</div>
			<% if can? :update, @document %>
			<!--
			<div id="stats">
				*coming soon*
			</div>
			-->
			<div id="settings">
				<h3>Settings</h3>
				<div class="content">
				<% if @new %>
					<p>Please save your new document first.<p>
				<% else %>
					<%= form_for(@document) do |f| %>
					  <%= render 'shared/error_messages', :object => f.object %>
					  <div class="field">
						<h4>Google Analytics</h4>
					    <%= f.text_field :stats_code %>
										<p class="small description">Enter your Google Analytics tracking code here to enable analytics (something like "UA-1234567-89").</p>

					  </div>
					  <div class="field">
						<h4>Make document private?</h4>
						<p>
						<span class="public">
							<%= f.label :public_true, "Public" %>
					    	<%= f.radio_button :public, true %>
						</span>
						<span class="private">
							<%= f.label :public_false, "Private" %>
							<%= f.radio_button :public, false %>
						</span>
						</p>
											<p class="small description">Choose "private" if you don't want your document to appear in public listings</p>

					  </div>
					  <div class="actions save <% if !@new %>ajax-save<% end %>">
					    <%= f.submit "Submit" %>
					
						<span class="loader"></span>
						<span class="success-indicator"></span>
						<span class="error-indicator"></span>
					  </div>
					<% end %>
				<% end %>
				
				</div>
			</div>
			<div id="typography">
				<h3>Typography</h3>
				<div class="content">
					<ul class="toolbar">
						<li><a class="button boldLink" href="#"><span>Make bold</span></a></li>
						<li><a class="button italicLink" href="#"><span>Make italic</span></a></li>
						<li><a class="button codeLink" href="#"><span>Wrap with PRE</span></a></li>
						<!--
						<li><a class="leftLink" href="#">Justify left</a></li>
						<li><a class="rightLink" href="#">Justify right</a></li>
						-->
						<li><a class="button linkLink" href="#"><span>Make link</span></a></li>
						<li><a class="button hrLink" href="#"><span>Insert HR</span></a></li>
						<li><a class="button ulLink" href="#"><span>Insert UL</span></a></li>
						<li><a class="button olLink" href="#"><span>Insert OL</span></a></li>
					</ul>
					<hr/>
					<ul>
						<li><a class="pLink" href="#">Make Paragraph</a></li>
						<li><a class="h2Link" href="#">Make h2</a></li>
						<li><a class="h3Link" href="#">Make h3</a></li>
						<li><a class="h4Link" href="#">Make h4</a></li>
						<li><a class="h5Link" href="#">Make h5</a></li>
					</ul>
					<!--
					<li>
						<select class="headerSelect">
							<option value="p">Paragraph</option>
							<option value="h2">H2</option>
							<option value="h3">H3</option>
							<option value="h4">H4</option>
							<option value="h4">H5</option>
						</select>
					</li>
					-->
					
				</div>
			</div>
		<% end %>
		</div>
</div>

app/views/documents/edit.html.erb
<%#= render 'shared/tinymce' %>
<%#= render 'shared/aloha' %>
<%= link_to "Back to document", document_path %><br/>
<%= form_for(@document) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :stats_code %><br />
    <%= f.text_area :stats_code %>
  </div>
  <div class="field">
    <%= f.label :public %><br />
    <%= f.text_area :public %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/documents/index.html.erb
<div class="documents">
	<ul>
  <%= render @document %>
	</ul>
</div>

app/views/documents/new.html.erb
<%= form_for(@document) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/documents/show.html.erb
<%#= render 'highlight' %>
<%#= render 'chili' %>
<%#= render 'documents/aloha' %>
<%= render 'documents/custom' %>

<% content_for :page_title do %>
	<%= @document.title %> | Documonk
<% end %>

<% content_for :head do %>

	<%= javascript_include_tag 'jquery-ui-1.8.10.custom.min' %>
	<%= javascript_include_tag 'jquery.hotkeys' %>
	<%= javascript_include_tag 'jquery.form' %>
	<%= javascript_include_tag 'autoresize.jquery.min' %>

	<%= javascript_include_tag 'jquery.tableofcontents' %>
	<%= javascript_include_tag 'monk.document.show' %>
	<%= javascript_include_tag 'fancybox/jquery.fancybox-1.3.4.pack' %>

	<% if @document.stats_code %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', '<%= @document.stats_code %>']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
	<% end %>

<% end %>

<%= render 'documents/palette' %>

<h1 class="instapaper_title"><%= @document.title %></h1>

<div id="content" class="show-wysiwyg">
	<div id="wysiwyg" class="not-editing instapaper_body">
		<%= raw Sanitize.clean(@document.content, Sanitize::Config::RELAXED) %>
	</div>
	<div id="source">
		<%= form_for(@document) do |f| %>
		  	<%= f.hidden_field :title %>
  			<%#= render 'shared/error_messages', :object => f.object %>
  			<%= f.text_area :content %>
		<% end %>
	</div>
</div>

app/views/layouts/_javascript.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>

<%= javascript_include_tag 'rails' %>
<%= javascript_include_tag 'monk.global' %>

app/views/notes/_note.html.erb
<li>
	<p><%= link_to note.content, note %></p>
	
	<% if can? :update, note %>
		<%= link_to "Edit", edit_note_path(note.id), :class => "small" %>
	<% end %>
	<% if can? :destroy, note %>
		| <%= link_to "Delete", note, :method => :delete, :confirm => "You sure?",
	                               :title => "Delete #{note.content}",:class => "small delete"  %>
	<% end %>

</li>

app/views/notes/index.html.erb
<h1>Notes for the document</h1>
<h3><%= link_to "New Note", new_note_path %></h3>
<ul class="notes">
  <%= render @notes %>
</ul>

app/views/notes/new.html.erb
<%= form_for(@note, :url => document_notes_url(@document)) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :note_type %><br />
    <%= f.text_field :note_type %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/notes/show.html.erb
<h4><%= link_to "< Back to notes", document_notes_path %></h4>

<ul>
	<li><strong>Type:</strong> <%= @note.note_type %></li>
	<li><strong>Document:</strong> <%= @note.document.title %></li>
	<li><strong>User:</strong> <%= @note.user.email %></li>
	<li><strong>Content:</strong> <%= @note.content %></li>
	<li><strong>Position:</strong> <%= @note.position %></li>
</ul>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/shared/_admin_nav.html.erb
<p>
<%= link_to "Users", users_path %> | <%= link_to "Documents", documents_path %>
</p>

app/views/shared/_login.html.erb
<div class="dialogs">
	<div id="login" class="dialog">
		<div class="sign-in">
		<h2>Sign In</h2>
		<p>Sign in to manage and edit your documents.</p>
	<%= form_for resource_name, resource, :url => session_path(resource_name) do |f| -%>
	  <%#= devise_error_messages! %>

	  <p><%= f.label :email %><br />
	  <%= f.text_field :email %></p>

	  <p><%= f.label :password %><br />
	  <%= f.password_field :password %></p>

	<%= f.hidden_field :remember_me %>
	<p class="small"><a href="/users/password/new" title="I forgot my password">I forgot my password!</a></p>

	<input type="hidden" id="redirect_to" name="redirect_to" value="<%= request.url %>" />

	  <p><%= f.submit "Sign in" %></p>
	

	<% end %>

	<%#= render :partial => "devise/shared/links" %>
		</div>

		<div class="sign-up">
		<h4>Don't have an account?</h4>
		<p>Signing up is free and only takes 30 seconds.</p>
	<%= form_for resource_name, resource, :url => registration_path(resource_name) do |f| -%>
	  <%#= devise_error_messages! %>

	  <p><%= f.label :email %><br />
	  <%= f.text_field :email %></p>

	  <p><%= f.label :password %><br />
	  <%= f.password_field :password %></p>
	
		<p><%= f.label :twitter_account %> (optional)<br />
	  <%= f.text_field :twitter_account %></p>

	<input type="hidden" id="redirect_to" name="redirect_to" value="<%= new_document_path %>" />

	  <p><%= f.submit "Sign up" %></p>
	<% end %>

	<%#= render :partial => "devise/shared/links" %>

		</div>
	</div>

	<div id="logout" class="dialog">
		<p>Are you sure you want to log out?</p>
		<a href="/users/sign_out?redirect_to=<%= request.url %>">Log Out</a>
	</div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.email, user %>
	<% if can? :update, user %>
		<%= link_to "Edit", edit_user_path(user.id), :class => "small" %>
	<% end %>
	<% if can? :destroy, user %>
		| <%= link_to "Delete", user, :method => :delete, :confirm => "You sure?",
	                               :title => "Delete #{user.email}",:class => "small delete"  %>
	<% end %>
</li>

app/views/users/show.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.email %>
</h1>
	<p><a href="/documents/new" class="button">Create new document</a></p>
<ul>
		<% if current_user.role?(:admin) %>
	<li><strong>Role:</strong> <%= @user.role! %> </li>
	<li><strong>URL:</strong>  <%= link_to user_path(@user), @user %></li>
		<% end %>
	<li><strong>Twitter:</strong>  <%= @user.twitter_account %></li>
	<li><% if can? :edit, @user %>
		<%= link_to "Edit", edit_user_path(@user) %>
	<% end %>
	</li>
</ul>
	
<br/>
<hr/>
<% unless @user.documents.empty? %>
  <div class="documents">
    <%= render @documents %>
  </div>
<% end %>